import React from "react";
import { FileText, Download, FileCode } from "lucide-react";
import type { SecurityIncident } from "../types";
import { getReportDownloadUrl } from "../api";

interface ReportTabProps {
  incident: SecurityIncident;
}

export const ReportTab: React.FC<ReportTabProps> = ({ incident }) => {
  const report = incident.report;
  const pdfUrl = getReportDownloadUrl(incident.id, "pdf");
  const mdUrl = getReportDownloadUrl(incident.id, "markdown");

  return (
    <div className="report-wrap">
      {/* Export card */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">
            <FileText size={16} color="var(--accent)" />
            <span>Incident Reports &amp; Sign-off</span>
          </div>
          <div style={{ display: "flex", gap: "8px" }}>
            <a
              href={mdUrl}
              target="_blank"
              rel="noreferrer"
              className="btn btn-ghost btn-sm"
              style={{ textDecoration: "none" }}
            >
              <FileCode size={14} />
              <span>Export Markdown</span>
            </a>
            <a
              href={pdfUrl}
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary btn-sm"
              style={{ textDecoration: "none" }}
            >
              <Download size={14} />
              <span>Download PDF</span>
            </a>
          </div>
        </div>

        <div className="card-body">
          <div style={{ fontSize: "12px", color: "var(--text-muted)", marginBottom: "16px" }}>
            Generated by <strong>SecOps Autonomous Agent</strong> &mdash; Audit signoff:{" "}
            <span className="mono">{report?.generated_at || incident.updated_at}</span>
          </div>

          {/* Executive summary */}
          <div style={{ marginBottom: "16px" }}>
            <div className="report-section-heading">Executive Summary</div>
            <div
              className="report-markdown"
              style={{ borderLeft: "3px solid var(--accent)" }}
            >
              {report?.executive_summary || incident.llm_reasoning}
            </div>
          </div>

          {/* Technical narrative */}
          <div>
            <div className="report-section-heading">Technical Investigation Narrative</div>
            <div
              className="report-markdown"
              style={{ borderLeft: "3px solid var(--border-medium)" }}
            >
              {report?.technical_narrative || (
                `Detailed investigation logs correlate ${incident.alert_count} alerts from Wazuh and Splunk. ` +
                `Attacker IP ${incident.entities.find((e) => e.type === "ip")?.value || "untrusted"} engaged in unauthorized command execution. ` +
                `Deterministic severity scoring calculated ${incident.deterministic_score}/100 and applied minimum floor constraint ${incident.deterministic_floor}.`
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
