import React from "react";
import { FileText, Download, FileCode } from "lucide-react";
import type { SecurityIncident } from "../types";
import { getReportDownloadUrl } from "../api";

interface ReportTabProps {
  incident: SecurityIncident;
}

export const ReportTab: React.FC<ReportTabProps> = ({ incident }) => {
  const report = incident.report;
  const pdfUrl = getReportDownloadUrl(incident.id, "pdf");
  const mdUrl = getReportDownloadUrl(incident.id, "markdown");

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
      {/* Export Action Card */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">
            <FileText size={16} color="var(--accent)" />
            <span>Executive & Technical Incident Reports</span>
          </div>

          <div style={{ display: "flex", gap: "10px" }}>
            <a
              href={mdUrl}
              target="_blank"
              rel="noreferrer"
              className="btn btn-ghost btn-sm"
              style={{ display: "flex", alignItems: "center", gap: "6px", textDecoration: "none" }}
            >
              <FileCode size={14} />
              <span>Export Markdown</span>
            </a>

            <a
              href={pdfUrl}
              target="_blank"
              rel="noreferrer"
              className="btn btn-primary btn-sm"
              style={{ display: "flex", alignItems: "center", gap: "6px", textDecoration: "none" }}
            >
              <Download size={14} />
              <span>Download Signed PDF</span>
            </a>
          </div>
        </div>

        <div className="card-body">
          <div style={{ fontSize: "12px", color: "var(--text-secondary)", marginBottom: "16px" }}>
            Generated by <strong>SecOps Agent (Autonomous Engine)</strong> ? Audit Signoff:{" "}
            <span className="mono">{report?.generated_at || incident.updated_at}</span>
          </div>

          {/* Executive Summary */}
          <div style={{ marginBottom: "24px" }}>
            <div
              style={{
                fontSize: "12px",
                fontWeight: 700,
                color: "var(--accent)",
                letterSpacing: "0.5px",
                marginBottom: "8px",
              }}
            >
              EXECUTIVE SUMMARY
            </div>
            <div
              style={{
                fontSize: "13px",
                lineHeight: "1.6",
                color: "var(--text-primary)",
                background: "rgba(0, 0, 0, 0.2)",
                padding: "14px",
                borderRadius: "6px",
                borderLeft: "3px solid var(--accent)",
              }}
            >
              {report?.executive_summary || incident.llm_reasoning}
            </div>
          </div>

          {/* Technical Narrative */}
          <div>
            <div
              style={{
                fontSize: "12px",
                fontWeight: 700,
                color: "#38bdf8",
                letterSpacing: "0.5px",
                marginBottom: "8px",
              }}
            >
              TECHNICAL INVESTIGATION NARRATIVE
            </div>
            <div
              style={{
                fontSize: "13px",
                lineHeight: "1.6",
                color: "var(--text-secondary)",
                background: "rgba(0, 0, 0, 0.2)",
                padding: "14px",
                borderRadius: "6px",
                borderLeft: "3px solid #38bdf8",
              }}
            >
              {report?.technical_narrative || (
                <div>
                  Detailed investigation logs correlate {incident.alert_count} alerts from Wazuh and Splunk.
                  Attacker IP {incident.entities.find((e) => e.type === "ip")?.value || "untrusted"} engaged in
                  unauthorized command execution. Deterministic severity scoring calculated{" "}
                  {incident.deterministic_score}/100 and applied minimum floor constraint{" "}
                  {incident.deterministic_floor}.
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
