"""
Elastic Security / Elasticsearch ECS Alert Adapter.
Normalizes Elastic Security signal/alert payloads formatted per Elastic Common Schema (ECS)
into unified NormalizedAlert instances:
- Maps ECS event.severity and rule.severity into SeverityLevel.
- Extracts CIM/ECS entity definitions (source.ip, destination.ip, user.name, host.hostname).
- Parses MITRE ATT&CK tactic and technique IDs from threat.tactic and threat.technique arrays.
- Handles both Kibana Alerting and Elastic Defend detection engine payloads.
"""
from typing import Dict, Any, List, Optional
import hashlib
import uuid
from backend.ingestion.base import AlertSourceAdapter
from backend.ingestion.models import (
    NormalizedAlert,
    SeverityLevel,
    AlertSourceType,
    EntityType,
    EntityRole,
    Entity,
    MitreAttackMetadata,
    utc_now,
)


class ElasticAdapter(AlertSourceAdapter):
    """
    Adapter for Elastic Security detection rules and ECS-formatted alerts.
    """

    @property
    def source_type(self) -> AlertSourceType:
        return AlertSourceType.ELASTIC

    _ECS_SEVERITY_MAP = {
        "informational": SeverityLevel.INFORMATIONAL,
        "info": SeverityLevel.INFORMATIONAL,
        "low": SeverityLevel.LOW,
        "medium": SeverityLevel.MEDIUM,
        "high": SeverityLevel.HIGH,
        "critical": SeverityLevel.CRITICAL,
    }

    def can_handle(self, payload: Dict[str, Any]) -> bool:
        if not isinstance(payload, dict):
            return False
        # Explicit source
        if payload.get("source") in ("elastic", "elasticsearch", "kibana"):
            return True
        # ECS / Kibana alert signatures
        if "kibana.alert" in payload or "signal" in payload:
            return True
        if "ecs" in payload or "ecs.version" in payload:
            return True
        if isinstance(payload.get("agent"), dict) and payload.get("agent", {}).get("type") in ("filebeat", "packetbeat", "elastic-endpoint", "auditbeat"):
            return True
        if "@timestamp" in payload and "rule" in payload:
            return True
        return False

    def normalize(self, payload: Dict[str, Any]) -> NormalizedAlert:
        # Resolve nested or flat ECS structures
        rule_obj = payload.get("rule", {}) or payload.get("signal", {}).get("rule", {})
        if not isinstance(rule_obj, dict):
            rule_obj = {}
        event_obj = payload.get("event", {})
        if not isinstance(event_obj, dict):
            event_obj = {}
        source_obj = payload.get("source", {})
        if not isinstance(source_obj, dict):
            source_obj = {}
        dest_obj = payload.get("destination", {})
        if not isinstance(dest_obj, dict):
            dest_obj = {}
        host_obj = payload.get("host", {})
        if not isinstance(host_obj, dict):
            host_obj = {}
        user_obj = payload.get("user", {})
        if not isinstance(user_obj, dict):
            user_obj = {}
        process_obj = payload.get("process", {})
        if not isinstance(process_obj, dict):
            process_obj = {}

        def get_field(*keys: str, default: Any = None) -> Any:
            for k in keys:
                if k in payload:
                    return payload[k]
            return default

        rule_id = (
            rule_obj.get("id")
            or get_field("signal.rule.id", "rule.id", "kibana.alert.rule.id")
            or f"ELASTIC-{uuid.uuid4().hex[:8].upper()}"
        )
        rule_name = (
            rule_obj.get("name")
            or get_field("signal.rule.name", "rule.name", "kibana.alert.rule.name")
            or "Elastic Detection Rule"
        )
        rule_description = (
            rule_obj.get("description")
            or get_field("signal.rule.description", "rule.description")
            or "Detection alert generated by Elastic Security"
        )

        raw_sev = (
            rule_obj.get("severity")
            or event_obj.get("severity")
            or get_field("signal.rule.severity", "kibana.alert.severity", "event.severity")
            or "medium"
        )
        normalized_severity = self._ECS_SEVERITY_MAP.get(str(raw_sev).lower(), SeverityLevel.MEDIUM)

        timestamp = (
            get_field("@timestamp", "event.created", "timestamp")
            or payload.get("@timestamp")
            or utc_now()
        )

        source_ip = source_obj.get("ip") or get_field("source.ip", "src_ip")
        dest_ip = dest_obj.get("ip") or get_field("destination.ip", "dest_ip")
        host_name = host_obj.get("hostname") or host_obj.get("name") or get_field("host.hostname", "host.name", "hostname", default="unknown")
        user_name = user_obj.get("name") or get_field("user.name", "username")
        process_name = process_obj.get("name") or get_field("process.name")

        entities: List[Entity] = []
        if source_ip:
            entities.append(Entity(type=EntityType.IP, value=str(source_ip), role=EntityRole.SOURCE))
        if dest_ip:
            entities.append(Entity(type=EntityType.IP, value=str(dest_ip), role=EntityRole.DESTINATION))
        if host_name and host_name != "unknown":
            entities.append(Entity(type=EntityType.HOST, value=str(host_name), role=EntityRole.TARGET))
        if user_name:
            entities.append(Entity(type=EntityType.USER, value=str(user_name), role=EntityRole.RELATED))

        threat_arr = rule_obj.get("threat", []) or payload.get("threat", [])
        mitre_tactics = []
        mitre_techniques = []
        if isinstance(threat_arr, list):
            for t in threat_arr:
                if isinstance(t, dict):
                    tactic = t.get("tactic", {})
                    if isinstance(tactic, dict) and "id" in tactic:
                        mitre_tactics.append(str(tactic["id"]))
                    techniques = t.get("technique", [])
                    if isinstance(techniques, list):
                        for tech in techniques:
                            if isinstance(tech, dict) and "id" in tech:
                                mitre_techniques.append(str(tech["id"]))

        mitre_metadata = MitreAttackMetadata(
            tactics=mitre_tactics,
            techniques=mitre_techniques,
        )

        fp_raw = f"elastic:{rule_id}:{host_name}:{source_ip}:{timestamp}"
        fingerprint = hashlib.sha256(fp_raw.encode()).hexdigest()
        alert_id = f"ELASTIC-{uuid.uuid4().hex[:12].upper()}"

        return NormalizedAlert(
            alert_id=alert_id,
            fingerprint=fingerprint,
            source=AlertSourceType.ELASTIC,
            rule_id=str(rule_id),
            rule_name=str(rule_name),
            rule_description=str(rule_description),
            raw_severity=str(raw_sev),
            normalized_severity=normalized_severity,
            timestamp=str(timestamp),
            host=str(host_name),
            source_ip=str(source_ip) if source_ip else None,
            destination_ip=str(dest_ip) if dest_ip else None,
            username=str(user_name) if user_name else None,
            process_name=str(process_name) if process_name else None,
            entities=entities,
            mitre_attack=mitre_metadata,
            raw_payload=payload,
        )
